# Airbnb NYC Listings — Data Cleaning & EDA

## Introduction

Real-world data is rarely clean. It comes with missing values, incorrect data types (like prices with $ signs), and inconsistencies. The Airbnb Open Data is a perfect example of this challenge.


This dataset contains Airbnb listings from New York City covering 
details like host information, location, room types, pricing, 
availability, and guest reviews across 25 columns.

---

## Approach

Before jumping into cleaning, we will first **understand the dataset**:
- What each column means
- Which columns are important for analysis
- What data quality issues exist

Only then we will proceed to **clean the data**.

---

## Objective
- Understand the raw Airbnb NYC dataset
- Identify and fix data quality issues such as:
  - Missing values
  - Incorrect data types
  - Duplicate records
  - Invalid values & outliers
  - Drop unnecessary columns

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Airbnb_Open_Data.csv")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17708\3424017332.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Airbnb_Open_Data.csv")

In [3]:
df.shape

(102599, 26)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

<h2 style="color:blue">Removal of Duplicates</h2>

In [5]:
df.duplicated().sum()

541

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(102058, 26)

In [8]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [9]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

<h2 style="color:blue">Dropping Unnecessary Columns</h2>

In [10]:
df.drop(columns=['host id','country','country code','license','house_rules'],inplace=True)

df.isnull().sum()

In [11]:
df.dtypes

id                                  int64
NAME                               object
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                 float64
price                              object
service fee                        object
minimum nights                    float64
number of reviews                 float64
last review                        object
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
dtype: object

<h2 style="color:blue">Filling null values</h2>

In [12]:
df.fillna(
    value={
        'name':'UNK',
        'host_identity_verified':'unconfirmed',
        'host name':'UNK host',
        'neighbourhood group':'UNK NHD GRP',
        'neighbourhood':'UNK NHD',
        'instant_bookable':df.instant_bookable.mode()[0],
        'availability 365':0,
        'minimum nights':0,
        'number of reviews':0,
        'reviews per month':0,
        'review rate number':0,
        'calculated host listings count':0,
        'availability 365':0,
        'Construction year':df['Construction year'].mode()[0],
        'cancellation_policy':df['cancellation_policy'].mode()[0],
        },inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17708\2629880966.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(

In [13]:
df.isnull().sum()

id                                    0
NAME                                250
host_identity_verified                0
host name                             0
neighbourhood group                   0
neighbourhood                         0
lat                                   8
long                                  8
instant_bookable                      0
cancellation_policy                   0
room type                             0
Construction year                     0
price                               247
service fee                         273
minimum nights                        0
number of reviews                     0
last review                       15832
reviews per month                     0
review rate number                    0
calculated host listings count        0
availability 365                      0
dtype: int64

In [14]:
df.head(5)

,id,NAME,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,...,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Clean & quiet apt home by the park,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,strict,...,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,moderate,...,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,unconfirmed,Elise,Manhattan,Harlem,40.80902,-73.94190,True,flexible,...,2005.0,$620,$124,3.0,0.0,NaN,0.00,5.0,1.0,352.0
3,1002755,NaN,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,True,moderate,...,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,moderate,...,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0

<h2 style="color:blue">Formatting Price Columns</h2>

In [15]:
df.price = df.price.str.replace('$',' ')

In [16]:
df.price.head(3)

0     966
1     142
2     620
Name: price, dtype: object

In [17]:
df.price = df.price.str.replace(',','')

In [18]:
df.price

0           966
1           142
2           620
3           368
4           204
           ...
102053      696
102054      909
102055      387
102056      848
102057     1128
Name: price, Length: 102058, dtype: object

In [19]:
df.dtypes

id                                  int64
NAME                               object
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
instant_bookable                     bool
cancellation_policy                object
room type                          object
Construction year                 float64
price                              object
service fee                        object
minimum nights                    float64
number of reviews                 float64
last review                        object
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
dtype: object

In [20]:
df['service fee'] = df['service fee'].str.replace('$','')

In [21]:
df['service fee'].head(10)

0    193
1     28
2    124
3     74
4     41
5    115
6     14
7    212
8    204
9     58
Name: service fee, dtype: object

<h2 style="color:blue">String Type Conversion</h2>

In [22]:
cols = ['NAME','host name','neighbourhood group','neighbourhood','instant_bookable','cancellation_policy','room type'] 
df[cols]= df[cols].astype(str)

In [23]:
df.dtypes

id                                  int64
NAME                               object
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                 float64
price                              object
service fee                        object
minimum nights                    float64
number of reviews                 float64
last review                        object
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
dtype: object

In [24]:
type(df['NAME'][0])  # will show <class 'str'>

str

In [25]:
# Clean and convert to numeric first
df['price'] = df['price'].astype(float)
df['service fee'] = df['service fee'].astype(float)

# Then fill NaN with group mean
df['price'] = df.groupby('room type')['price'].transform(lambda x: x.fillna(x.mean().round()))
df['service fee'] = df.groupby('room type')['service fee'].transform(lambda x: x.fillna(x.mean().round()))

In [26]:
df.drop(columns = ['last review'],inplace=True)

In [27]:
df.head(2)

,id,NAME,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Clean & quiet apt home by the park,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,strict,Private room,2020.0,966.0,193.0,10.0,9.0,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,moderate,Entire home/apt,2007.0,142.0,28.0,30.0,45.0,0.38,4.0,2.0,228.0

<h2 style="color:blue">Removed null values</h2>

In [28]:
df.isnull().sum()

id                                0
NAME                              0
host_identity_verified            0
host name                         0
neighbourhood group               0
neighbourhood                     0
lat                               8
long                              8
instant_bookable                  0
cancellation_policy               0
room type                         0
Construction year                 0
price                             0
service fee                       0
minimum nights                    0
number of reviews                 0
reviews per month                 0
review rate number                0
calculated host listings count    0
availability 365                  0
dtype: int64

In [29]:
df.dtypes

id                                  int64
NAME                               object
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                 float64
price                             float64
service fee                       float64
minimum nights                    float64
number of reviews                 float64
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
dtype: object

In [30]:
df.max()

id                                                                         57367417
NAME                              🪴🛋🌞 Unique sunny clean brownstone studio 1st f...
host_identity_verified                                                     verified
host name                                                                        현선
neighbourhood group                                                        manhatan
neighbourhood                                                              Woodside
lat                                                                        40.91697
long                                                                      -73.70522
instant_bookable                                                               True
cancellation_policy                                                          strict
room type                                                               Shared room
Construction year                                                            2022.0
price                                                                        1200.0
service fee                                                                   240.0
minimum nights                                                               5645.0
number of reviews                                                            1024.0
reviews per month                                                              90.0
review rate number                                                              5.0
calculated host listings count                                                332.0
availability 365                                                             3677.0
dtype: object

<h2 style="color:blue">Handling Outliers</h2>

In [31]:
print(df[df['minimum nights']>365].shape[0])
print(df[df['availability 365']>365].shape[0])

35
2754

In [32]:
#using clip() instead of completely removing them 
df['minimum nights'] = df['minimum nights'].clip(upper=365)
df['availability 365'] = df['availability 365'].clip(upper=365)

In [33]:
print(df[df['availability 365']>365].shape[0])
print(df[df['minimum nights']>365].shape[0])

0
0

In [34]:
df.dtypes

id                                  int64
NAME                               object
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                 float64
price                             float64
service fee                       float64
minimum nights                    float64
number of reviews                 float64
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
dtype: object

In [35]:
df.max()

id                                                                         57367417
NAME                              🪴🛋🌞 Unique sunny clean brownstone studio 1st f...
host_identity_verified                                                     verified
host name                                                                        현선
neighbourhood group                                                        manhatan
neighbourhood                                                              Woodside
lat                                                                        40.91697
long                                                                      -73.70522
instant_bookable                                                               True
cancellation_policy                                                          strict
room type                                                               Shared room
Construction year                                                            2022.0
price                                                                        1200.0
service fee                                                                   240.0
minimum nights                                                                365.0
number of reviews                                                            1024.0
reviews per month                                                              90.0
review rate number                                                              5.0
calculated host listings count                                                332.0
availability 365                                                              365.0
dtype: object

<h2 style="color:blue">Checking Unique Values</h2>

In [36]:
print(df['neighbourhood group'].unique())
print(df['neighbourhood'].unique())
print(df['host_identity_verified'].unique())
print(df['cancellation_policy'].unique())
print(df['room type'].unique())

['Brooklyn' 'Manhattan' 'brookln' 'manhatan' 'Queens' 'UNK NHD GRP'
 'Staten Island' 'Bronx']
['Kensington' 'Midtown' 'Harlem' 'Clinton Hill' 'East Harlem'
 'Murray Hill' 'Bedford-Stuyvesant' "Hell's Kitchen" 'Upper West Side'
 'Chinatown' 'South Slope' 'West Village' 'Williamsburg' 'Fort Greene'
 'Chelsea' 'Crown Heights' 'Park Slope' 'Windsor Terrace' 'Inwood'
 'East Village' 'Greenpoint' 'Bushwick' 'Flatbush' 'Lower East Side'
 'Prospect-Lefferts Gardens' 'Long Island City' 'Kips Bay' 'SoHo'
 'Upper East Side' 'Prospect Heights' 'Washington Heights' 'Woodside'
 'Brooklyn Heights' 'Carroll Gardens' 'Gowanus' 'Flatlands' 'Cobble Hill'
 'Flushing' 'Boerum Hill' 'Sunnyside' 'DUMBO' 'St. George' 'Highbridge'
 'Financial District' 'Ridgewood' 'Morningside Heights' 'Jamaica'
 'Middle Village' 'NoHo' 'Ditmars Steinway' 'Flatiron District'
 'Roosevelt Island' 'Greenwich Village' 'Little Italy' 'East Flatbush'
 'Tompkinsville' 'Astoria' 'Clason Point' 'Eastchester' 'Kingsbridge'
 'Two Bridges' 'Queens Village' 'Rockaway Beach' 'Forest Hills' 'Nolita'
 'Woodlawn' 'University Heights' 'Gravesend' 'Gramercy' 'Allerton'
 'UNK NHD' 'East New York' 'Theater District' 'Concourse Village'
 'Sheepshead Bay' 'Emerson Hill' 'Fort Hamilton' 'Bensonhurst' 'Tribeca'
 'Shore Acres' 'Sunset Park' 'Concourse' 'Elmhurst' 'Brighton Beach'
 'Jackson Heights' 'Cypress Hills' 'St. Albans' 'Arrochar' 'Rego Park'
 'Wakefield' 'Clifton' 'Bay Ridge' 'Graniteville' 'Spuyten Duyvil'
 'Stapleton' 'Briarwood' 'Ozone Park' 'Columbia St' 'Vinegar Hill'
 'Mott Haven' 'Longwood' 'Canarsie' 'Battery Park City' 'Civic Center'
 'East Elmhurst' 'New Springville' 'Morris Heights' 'Arverne'
 'Cambria Heights' 'Tottenville' 'Mariners Harbor' 'Concord'
 'Borough Park' 'Bayside' 'Downtown Brooklyn' 'Port Morris' 'Fieldston'
 'Kew Gardens' 'Midwood' 'College Point' 'Mount Eden' 'City Island'
 'Glendale' 'Port Richmond' 'Red Hook' 'Richmond Hill' 'Bellerose'
 'Maspeth' 'Williamsbridge' 'Soundview' 'Woodhaven' 'Woodrow' 'Co-op City'
 'Stuyvesant Town' 'Parkchester' 'North Riverdale' 'Dyker Heights'
 'Bronxdale' 'Sea Gate' 'Riverdale' 'Kew Gardens Hills' 'Bay Terrace'
 'Norwood' 'Claremont Village' 'Whitestone' 'Fordham' 'Bayswater'
 'Navy Yard' 'Brownsville' 'Eltingville' 'Fresh Meadows' 'Mount Hope'
 'Lighthouse Hill' 'Springfield Gardens' 'Howard Beach' 'Belle Harbor'
 'Jamaica Estates' 'Van Nest' 'Morris Park' 'West Brighton' 'Far Rockaway'
 'South Ozone Park' 'Tremont' 'Corona' 'Great Kills' 'Manhattan Beach'
 'Marble Hill' 'Dongan Hills' 'Castleton Corners' 'East Morrisania'
 'Hunts Point' 'Neponsit' 'Pelham Bay' 'Randall Manor' 'Throgs Neck'
 'Todt Hill' 'West Farms' 'Silver Lake' 'Morrisania' 'Laurelton'
 'Grymes Hill' 'Holliswood' 'Pelham Gardens' 'Belmont' 'Rosedale'
 'Edgemere' 'New Brighton' 'Midland Beach' 'Baychester' 'Melrose'
 'Bergen Beach' 'Richmondtown' 'Howland Hook' 'Schuylerville'
 'Coney Island' 'New Dorp Beach' "Prince's Bay" 'South Beach' 'Bath Beach'
 'Jamaica Hills' 'Oakwood' 'Castle Hill' 'Hollis' 'Douglaston' 'Huguenot'
 'Olinville' 'Edenwald' 'Grant City' 'Westerleigh'
 'Bay Terrace, Staten Island' 'Westchester Square' 'Little Neck'
 'Fort Wadsworth' 'Rosebank' 'Unionport' 'Mill Basin' 'Arden Heights'
 "Bull's Head" 'New Dorp' 'Rossville' 'Breezy Point' 'Willowbrook'
 'Glen Oaks' 'Gerritsen Beach' 'Chelsea, Staten Island']
['unconfirmed' 'verified']
['strict' 'moderate' 'flexible']
['Private room' 'Entire home/apt' 'Shared room' 'Hotel room']

<h2 style="color:blue">Standardizing Text Columns</h2>

In [37]:
df['neighbourhood group']=df['neighbourhood group'].str.replace('brookln','Brooklyn')
df['neighbourhood group']=df['neighbourhood group'].str.replace('manhatan','Manhattan')

<h2 style="color:blue">Capitalizing Column Values</h2>

In [38]:
cols = ['neighbourhood group', 'neighbourhood', 'host_identity_verified','room type', 'cancellation_policy']
for col in cols:
    df[col] = df[col].str.strip().str.title()

In [39]:
cols = ['neighbourhood group', 'neighbourhood', 'host_identity_verified','room type', 'cancellation_policy']
for col in cols:
    print(df[col].unique())

['Brooklyn' 'Manhattan' 'Queens' 'Unk Nhd Grp' 'Staten Island' 'Bronx']
['Kensington' 'Midtown' 'Harlem' 'Clinton Hill' 'East Harlem'
 'Murray Hill' 'Bedford-Stuyvesant' "Hell'S Kitchen" 'Upper West Side'
 'Chinatown' 'South Slope' 'West Village' 'Williamsburg' 'Fort Greene'
 'Chelsea' 'Crown Heights' 'Park Slope' 'Windsor Terrace' 'Inwood'
 'East Village' 'Greenpoint' 'Bushwick' 'Flatbush' 'Lower East Side'
 'Prospect-Lefferts Gardens' 'Long Island City' 'Kips Bay' 'Soho'
 'Upper East Side' 'Prospect Heights' 'Washington Heights' 'Woodside'
 'Brooklyn Heights' 'Carroll Gardens' 'Gowanus' 'Flatlands' 'Cobble Hill'
 'Flushing' 'Boerum Hill' 'Sunnyside' 'Dumbo' 'St. George' 'Highbridge'
 'Financial District' 'Ridgewood' 'Morningside Heights' 'Jamaica'
 'Middle Village' 'Noho' 'Ditmars Steinway' 'Flatiron District'
 'Roosevelt Island' 'Greenwich Village' 'Little Italy' 'East Flatbush'
 'Tompkinsville' 'Astoria' 'Clason Point' 'Eastchester' 'Kingsbridge'
 'Two Bridges' 'Queens Village' 'Rockaway Beach' 'Forest Hills' 'Nolita'
 'Woodlawn' 'University Heights' 'Gravesend' 'Gramercy' 'Allerton'
 'Unk Nhd' 'East New York' 'Theater District' 'Concourse Village'
 'Sheepshead Bay' 'Emerson Hill' 'Fort Hamilton' 'Bensonhurst' 'Tribeca'
 'Shore Acres' 'Sunset Park' 'Concourse' 'Elmhurst' 'Brighton Beach'
 'Jackson Heights' 'Cypress Hills' 'St. Albans' 'Arrochar' 'Rego Park'
 'Wakefield' 'Clifton' 'Bay Ridge' 'Graniteville' 'Spuyten Duyvil'
 'Stapleton' 'Briarwood' 'Ozone Park' 'Columbia St' 'Vinegar Hill'
 'Mott Haven' 'Longwood' 'Canarsie' 'Battery Park City' 'Civic Center'
 'East Elmhurst' 'New Springville' 'Morris Heights' 'Arverne'
 'Cambria Heights' 'Tottenville' 'Mariners Harbor' 'Concord'
 'Borough Park' 'Bayside' 'Downtown Brooklyn' 'Port Morris' 'Fieldston'
 'Kew Gardens' 'Midwood' 'College Point' 'Mount Eden' 'City Island'
 'Glendale' 'Port Richmond' 'Red Hook' 'Richmond Hill' 'Bellerose'
 'Maspeth' 'Williamsbridge' 'Soundview' 'Woodhaven' 'Woodrow' 'Co-Op City'
 'Stuyvesant Town' 'Parkchester' 'North Riverdale' 'Dyker Heights'
 'Bronxdale' 'Sea Gate' 'Riverdale' 'Kew Gardens Hills' 'Bay Terrace'
 'Norwood' 'Claremont Village' 'Whitestone' 'Fordham' 'Bayswater'
 'Navy Yard' 'Brownsville' 'Eltingville' 'Fresh Meadows' 'Mount Hope'
 'Lighthouse Hill' 'Springfield Gardens' 'Howard Beach' 'Belle Harbor'
 'Jamaica Estates' 'Van Nest' 'Morris Park' 'West Brighton' 'Far Rockaway'
 'South Ozone Park' 'Tremont' 'Corona' 'Great Kills' 'Manhattan Beach'
 'Marble Hill' 'Dongan Hills' 'Castleton Corners' 'East Morrisania'
 'Hunts Point' 'Neponsit' 'Pelham Bay' 'Randall Manor' 'Throgs Neck'
 'Todt Hill' 'West Farms' 'Silver Lake' 'Morrisania' 'Laurelton'
 'Grymes Hill' 'Holliswood' 'Pelham Gardens' 'Belmont' 'Rosedale'
 'Edgemere' 'New Brighton' 'Midland Beach' 'Baychester' 'Melrose'
 'Bergen Beach' 'Richmondtown' 'Howland Hook' 'Schuylerville'
 'Coney Island' 'New Dorp Beach' "Prince'S Bay" 'South Beach' 'Bath Beach'
 'Jamaica Hills' 'Oakwood' 'Castle Hill' 'Hollis' 'Douglaston' 'Huguenot'
 'Olinville' 'Edenwald' 'Grant City' 'Westerleigh'
 'Bay Terrace, Staten Island' 'Westchester Square' 'Little Neck'
 'Fort Wadsworth' 'Rosebank' 'Unionport' 'Mill Basin' 'Arden Heights'
 "Bull'S Head" 'New Dorp' 'Rossville' 'Breezy Point' 'Willowbrook'
 'Glen Oaks' 'Gerritsen Beach' 'Chelsea, Staten Island']
['Unconfirmed' 'Verified']
['Private Room' 'Entire Home/Apt' 'Shared Room' 'Hotel Room']
['Strict' 'Moderate' 'Flexible']

In [40]:
df.head()

,id,NAME,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Clean & quiet apt home by the park,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private Room,2020.0,966.0,193.0,10.0,9.0,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire Home/Apt,2007.0,142.0,28.0,30.0,45.0,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,Unconfirmed,Elise,Manhattan,Harlem,40.80902,-73.94190,True,Flexible,Private Room,2005.0,620.0,124.0,3.0,0.0,0.00,5.0,1.0,352.0
3,1002755,nan,Unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,True,Moderate,Entire Home/Apt,2005.0,368.0,74.0,30.0,270.0,4.64,4.0,1.0,322.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,Moderate,Entire Home/Apt,2009.0,204.0,41.0,10.0,9.0,0.10,3.0,1.0,289.0

<h2 style="color:blue">Renaming Column Names</h2>

In [41]:
df.rename(columns={'NAME':'name'},inplace=True)

In [42]:
df.head(2)

,id,name,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Clean & quiet apt home by the park,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private Room,2020.0,966.0,193.0,10.0,9.0,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire Home/Apt,2007.0,142.0,28.0,30.0,45.0,0.38,4.0,2.0,228.0

In [43]:
df.columns = df.columns.str.strip().str.lower().str.replace('_'," ")

In [44]:
df.columns

Index(['id', 'name', 'host identity verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long',
       'instant bookable', 'cancellation policy', 'room type',
       'construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'reviews per month', 'review rate number',
       'calculated host listings count', 'availability 365'],
      dtype='object')

In [45]:
df.head()

,id,name,host identity verified,host name,neighbourhood group,neighbourhood,lat,long,instant bookable,cancellation policy,room type,construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Clean & quiet apt home by the park,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private Room,2020.0,966.0,193.0,10.0,9.0,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire Home/Apt,2007.0,142.0,28.0,30.0,45.0,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,Unconfirmed,Elise,Manhattan,Harlem,40.80902,-73.94190,True,Flexible,Private Room,2005.0,620.0,124.0,3.0,0.0,0.00,5.0,1.0,352.0
3,1002755,nan,Unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,True,Moderate,Entire Home/Apt,2005.0,368.0,74.0,30.0,270.0,4.64,4.0,1.0,322.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,Moderate,Entire Home/Apt,2009.0,204.0,41.0,10.0,9.0,0.10,3.0,1.0,289.0

<h2 style="color:blue">Converting Float to Int</h2>

In [46]:
cols = ['construction year','price','service fee','minimum nights','number of reviews','reviews per month','review rate number','calculated host listings count','availability 365']
for col in cols:
    df[col]=df[col].astype(int)

In [47]:
df.dtypes

id                                  int64
name                               object
host identity verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
instant bookable                   object
cancellation policy                object
room type                          object
construction year                   int32
price                               int32
service fee                         int32
minimum nights                      int32
number of reviews                   int32
reviews per month                   int32
review rate number                  int32
calculated host listings count      int32
availability 365                    int32
dtype: object

In [48]:
df.head(3)

,id,name,host identity verified,host name,neighbourhood group,neighbourhood,lat,long,instant bookable,cancellation policy,room type,construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
0,1001254,Clean & quiet apt home by the park,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,Strict,Private Room,2020,966,193,10,9,0,4,6,286
1,1002102,Skylit Midtown Castle,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,Moderate,Entire Home/Apt,2007,142,28,30,45,0,4,2,228
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,Unconfirmed,Elise,Manhattan,Harlem,40.80902,-73.94190,True,Flexible,Private Room,2005,620,124,3,0,0,5,1,352

In [49]:
df.shape

(102058, 20)