<h2 style="color:green">Basics of Pandas</h2>

In [3]:
import pandas as pd
df = pd.read_csv("nyc_weather.csv")

In [4]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [5]:
df.shape

(31, 11)

In [6]:
df['Temperature'].max()

50

In [7]:
df['EST'][df['Events']=="Rain"]

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [8]:
df.fillna(0,inplace=True)

In [9]:
df['WindSpeedMPH'].mean()

6.225806451612903

In [10]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,0,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,0,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,0,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,0,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333

In [11]:
df.shape

(31, 11)

In [12]:
rows , cols = df.shape

In [13]:
df.tail()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,0,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,0,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,0,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,0,241

In [14]:
df[4:9]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,0,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,0,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,0,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76

In [15]:
df['Temperature']

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [16]:
df.Temperature

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [17]:
df[['Temperature','Humidity','Events']]

    Temperature  Humidity    Events
0            38        52         0
1            36        46         0
2            40        47         0
3            25        44         0
4            20        41         0
5            33        35         0
6            39        33         0
7            39        64         0
8            44        77      Rain
9            50        71      Rain
10           33        37         0
11           35        53         0
12           26        42         0
13           30        47         0
14           43        62         0
15           47        70      Rain
16           36        66  Fog-Snow
17           25        53      Snow
18           22        42         0
19           32        49         0
20           31        45         0
21           26        41      Snow
22           26        78  Fog-Snow
23           28        53      Snow
24           34        54         0
25           43        56         0
26           41        45      Rain
27           37        51         0
28           36        50         0
29           34        46         0
30           46        52         0

In [18]:
df['Temperature'][df.Temperature == df.Temperature.max()]

9    50
Name: Temperature, dtype: int64

In [19]:
df[['Temperature','Humidity']][df['Humidity']==df['Humidity'].max()]

    Temperature  Humidity
22           26        78

In [20]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.225806,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,3.422569,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,0.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.000000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [21]:
df.VisibilityMiles.max()

10

In [22]:
df.set_index('Temperature')

,EST,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Temperature,,,,,,,,,,
38,1/1/2016,23,52,30.03,10,8.0,0,5,0,281
36,1/2/2016,18,46,30.02,10,7.0,0,3,0,275
40,1/3/2016,21,47,29.86,10,8.0,0,1,0,277
25,1/4/2016,9,44,30.05,10,9.0,0,3,0,345
20,1/5/2016,-3,41,30.57,10,5.0,0,0,0,333
33,1/6/2016,4,35,30.50,10,4.0,0,0,0,259
39,1/7/2016,11,33,30.28,10,2.0,0,3,0,293
39,1/8/2016,29,64,30.20,10,4.0,0,8,0,79
44,1/9/2016,38,77,30.16,9,8.0,T,8,Rain,76
50,1/10/2016,46,71,29.59,4,0.0,1.8,7,Rain,109
33,1/11/2016,8,37,29.92,10,0.0,0,1,0,289
35,1/12/2016,15,53,29.85,10,6.0,T,4,0,235
26,1/13/2016,4,42,29.94,10,10.0,0,0,0,284
30,1/14/2016,12,47,29.95,10,5.0,T,7,0,266
43,1/15/2016,31,62,29.82,9,5.0,T,2,0,101
47,1/16/2016,37,70,29.52,8,7.0,0.24,7,Rain,340
36,1/17/2016,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
25,1/18/2016,6,53,29.83,9,12.0,T,2,Snow,293
22,1/19/2016,3,42,30.03,10,11.0,0,1,0,293
32,1/20/2016,15,49,30.13,10,6.0,0,2,0,302
31,1/21/2016,11,45,30.15,10,6.0,0,1,0,312
26,1/22/2016,6,41,30.21,9,0.0,0.01,3,Snow,34
26,1/23/2016,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
28,1/24/2016,11,53,29.92,8,6.0,T,3,Snow,327
34,1/25/2016,18,54,30.25,10,3.0,0,2,0,286
43,1/26/2016,29,56,30.03,10,7.0,0,2,0,244
41,1/27/2016,22,45,30.03,10,7.0,T,3,Rain,311
37,1/28/2016,20,51,29.90,10,5.0,0,1,0,234
36,1/29/2016,21,50,29.58,10,8.0,0,4,0,298
34,1/30/2016,16,46,30.01,10,7.0,0,0,0,257
46,1/31/2016,28,52,29.90,10,5.0,0,0,0,241

In [23]:
df.reset_index(inplace=True)

In [24]:
df.head(1)

,index,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,0,1/1/2016,38,23,52,30.03,10,8.0,0,5,0,281

In [25]:
df.loc[38]

KeyError: 38

<h2 style="color:green">Different Ways of Creating Dataframe</h2>

In [26]:
#way 1 (python dictionary list)
weather_data = {
'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
'temperature': [32, 35, 28],
'windspeed': [6,7,2],
'event': ['Rain', 'Sunny', 'Snow']
}


df = pd.DataFrame(weather_data)

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [27]:

# way 2 (python tuple list)
weather_data = [
('1/1/2017', 32, 6, 'Rain'),
('1/2/2017', 35, 7, 'Sunny'),
('1/3/2017', 28, 2, 'Snow')
]

df = pd.DataFrame(weather_data,columns=["day",'temp',"speed","event"])

In [28]:
df

        day  temp  speed  event
0  1/1/2017    32      6   Rain
1  1/2/2017    35      7  Sunny
2  1/3/2017    28      2   Snow

In [29]:
# way 3 (python dictionary list)
weather_data = [
{'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
{'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
{'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'}
]

df = pd.DataFrame(weather_data)

In [30]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [66]:
import pandas as pd
df = pd.read_csv("weather_data.csv",parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

<h2 style="color:green">fillna()</h2>

In [67]:
df.fillna(0)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          0.0        9.0   Sunny
2 2017-01-05         28.0        0.0    Snow
3 2017-01-06          0.0        7.0       0
4 2017-01-07         32.0        0.0    Rain
5 2017-01-08          0.0        0.0   Sunny
6 2017-01-09          0.0        0.0       0
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [68]:
df.ffill()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        7.0   Sunny
6 2017-01-09         32.0        7.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [69]:
df.bfill()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.0    Rain
5 2017-01-08         34.0        8.0   Sunny
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [70]:
df.fillna(method="ffill",axis="columns")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7560\780816820.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill",axis="columns")
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7560\780816820.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(method="ffill",axis="columns")

,day,temperature,windspeed,event
0,2017-01-01 00:00:00,32.0,6.0,Rain
1,2017-01-04 00:00:00,2017-01-04 00:00:00,9.0,Sunny
2,2017-01-05 00:00:00,28.0,28.0,Snow
3,2017-01-06 00:00:00,2017-01-06 00:00:00,7.0,7.0
4,2017-01-07 00:00:00,32.0,32.0,Rain
5,2017-01-08 00:00:00,2017-01-08 00:00:00,2017-01-08 00:00:00,Sunny
6,2017-01-09 00:00:00,2017-01-09 00:00:00,2017-01-09 00:00:00,2017-01-09 00:00:00
7,2017-01-10 00:00:00,34.0,8.0,Cloudy
8,2017-01-11 00:00:00,40.0,12.0,Sunny

In [71]:
df.ffill(axis="columns")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7560\2963746082.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.ffill(axis="columns")

,day,temperature,windspeed,event
0,2017-01-01 00:00:00,32.0,6.0,Rain
1,2017-01-04 00:00:00,2017-01-04 00:00:00,9.0,Sunny
2,2017-01-05 00:00:00,28.0,28.0,Snow
3,2017-01-06 00:00:00,2017-01-06 00:00:00,7.0,7.0
4,2017-01-07 00:00:00,32.0,32.0,Rain
5,2017-01-08 00:00:00,2017-01-08 00:00:00,2017-01-08 00:00:00,Sunny
6,2017-01-09 00:00:00,2017-01-09 00:00:00,2017-01-09 00:00:00,2017-01-09 00:00:00
7,2017-01-10 00:00:00,34.0,8.0,Cloudy
8,2017-01-11 00:00:00,40.0,12.0,Sunny

In [72]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [73]:
df = pd.read_csv("weather_data.csv",parse_dates=["day"])

In [74]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [75]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

<h2 style="color:green">interpolate()</h2>

In [76]:
df = df.infer_objects(copy=False)
df = df.interpolate(numeric_only=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7560\1279419521.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df = df.interpolate(numeric_only=True)

In [77]:
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].interpolate()

In [78]:
df

         day  temperature  windspeed   event
0 2017-01-01    32.000000       6.00    Rain
1 2017-01-04    30.000000       9.00   Sunny
2 2017-01-05    28.000000       8.00    Snow
3 2017-01-06    30.000000       7.00     NaN
4 2017-01-07    32.000000       7.25    Rain
5 2017-01-08    32.666667       7.50   Sunny
6 2017-01-09    33.333333       7.75     NaN
7 2017-01-10    34.000000       8.00  Cloudy
8 2017-01-11    40.000000      12.00   Sunny

<h2 style="color:green">dropna()</h2>

In [81]:
df.dropna()

         day  temperature  windspeed   event
0 2017-01-01    32.000000       6.00    Rain
1 2017-01-04    30.000000       9.00   Sunny
2 2017-01-05    28.000000       8.00    Snow
4 2017-01-07    32.000000       7.25    Rain
5 2017-01-08    32.666667       7.50   Sunny
7 2017-01-10    34.000000       8.00  Cloudy
8 2017-01-11    40.000000      12.00   Sunny

In [82]:
df.dropna(how="all")

         day  temperature  windspeed   event
0 2017-01-01    32.000000       6.00    Rain
1 2017-01-04    30.000000       9.00   Sunny
2 2017-01-05    28.000000       8.00    Snow
3 2017-01-06    30.000000       7.00     NaN
4 2017-01-07    32.000000       7.25    Rain
5 2017-01-08    32.666667       7.50   Sunny
6 2017-01-09    33.333333       7.75     NaN
7 2017-01-10    34.000000       8.00  Cloudy
8 2017-01-11    40.000000      12.00   Sunny

In [90]:
df.dropna(thresh=1)

         day  temperature  windspeed   event
0 2017-01-01    32.000000       6.00    Rain
1 2017-01-04    30.000000       9.00   Sunny
2 2017-01-05    28.000000       8.00    Snow
3 2017-01-06    30.000000       7.00     NaN
4 2017-01-07    32.000000       7.25    Rain
5 2017-01-08    32.666667       7.50   Sunny
6 2017-01-09    33.333333       7.75     NaN
7 2017-01-10    34.000000       8.00  Cloudy
8 2017-01-11    40.000000      12.00   Sunny