In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a[0]

1

In [4]:
a[1]

2

In [5]:
a.size

4

In [6]:
a.len()

AttributeError: 'numpy.ndarray' object has no attribute 'len'

In [7]:
help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any object that can be interpreted as a numpy data type.
 |  buffer : object exposing buffer interface, optional
 |      Used to fill the array with data.
 |  offset : int, optional
 |      Offset of array data in buffer.
 |  strides : tuple of ints, optional
 |      Strides of data in memory.
 |  order : {'C', 'F'}, optional
 |      Row-major (C-style) or column-major (Fortran-style) order.
 |
 |  Attributes
 |  ----------
 |  T : ndarray
 |      Transpose of the array.
 |  data : buffer
 |      The array's elements, in memory.
 |  dtype : dtype object
 |      Describes the format of the elements in the array.
 |  flags : dict
 |      Dictionary containing information related to memory use, e.g.,
 |      'C_CONTIGUOUS', 'OWNDATA', 'WRITEABLE', etc.
 |  flat : numpy.flatiter object
 |      Flattened version of the array as an iterator.  The iterator
 |      allows assignments, e.g., ``x.flat = 3`` (See `ndarray.flat` for
 |      assignment examples; TODO).
 |  imag : ndarray
 |      Imaginary part of the array.
 |  real : ndarray
 |      Real part of the array.
 |  size : int
 |      Number of elements in the array.
 |  itemsize : int
 |      The memory use of each array element in bytes.
 |  nbytes : int
 |      The total number of bytes required to store the array data,
 |      i.e., ``itemsize * size``.
 |  ndim : int
 |      The array's number of dimensions.
 |  shape : tuple of ints
 |      Shape of the array.
 |  strides : tuple of ints
 |      The step-size required to move from one element to the next in
 |      memory. For example, a contiguous ``(3, 4)`` array of type
 |      ``int16`` in C-order has strides ``(8, 2)``.  This implies that
 |      to move from element to element in memory requires jumps of 2 bytes.
 |      To move from row-to-row, one needs to jump 8 bytes at a time
 |      (``2 * 4``).
 |  ctypes : ctypes object
 |      Class containing properties of the array needed for interaction
 |      with ctypes.
 |  base : ndarray
 |      If the array is a view into another array, that array is its `base`
 |      (unless that array is also a view).  The `base` array is where the
 |      array data is actually stored.
 |
 |  See Also
 |  --------
 |  array : Construct an array.
 |  zeros : Create an array, each element of which is zero.
 |  empty : Create an array, but leave its allocated memory unchanged (i.e.,
 |          it contains "garbage").
 |  dtype : Create a data-type.
 |  numpy.typing.NDArray : An ndarray alias :term:`generic <generic type>`
 |                         w.r.t. its `dtype.type <numpy.dtype.type>`.
 |
 |  Notes
 |  -----
 |  There are two modes of creating an array using ``__new__``:
 |
 |  1. If `buffer` is None, then only `shape`, `dtype`, and `order`
 |     are used.
 |  2. If `buffer` is an object exposing the buffer interface, then
 |     all keywords are interpreted.
 |
 |  No ``__init__`` method is needed because the array is fully initialized
 |  after the ``__new__`` method.
 |
 |  Examples
 |  --------
 |  These examples illustrate the low-level `ndarray` constructor.  Refer
 |  to the `See Also` section above for easier ways of constructing an
 |  ndarray.
 |
 |  First mode, `buffer` is None:
 |
 |  >>> np.ndarray(shape=(2,2), dtype=float, order='F')
 |  array([[0.0e+000, 0.0e+000], # random
 |         [     nan, 2.5e-323]])
 |
 |  Second mode:
 |
 |  >>> np.ndarray((2,), buffer=np.array([1,2,3]),
 |  ...            offset=np.int_().itemsize,
 |  ...            dtype=int) # offset = 1*itemsize, i.e. skip first element
 |  array([2, 3])
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __array__(...)
 |      a.__array__([dtype], /)
 |
 |      Returns either a new reference to self if dtype is not given or a new array
 |      of provided data type if dtype is different from the current dtype of the
 |      array.
 |
 |  __array_finalize__(...)
 |      a.__array_finalize__(obj, /)
 |
 |      Present so subclasses can call super. Does nothing.
 |
 |  __array_function__(...)
 |
 |  __array_prepare__(...)
 |      a.__array_prepare__(array[, context], /)
 |
 |      Returns a view of `array` with the same type as self.
 |
 |  __array_ufunc__(...)
 |
 |  __array_wrap__(...)
 |      a.__array_wrap__(array[, context], /)
 |
 |      Returns a view of `array` with the same type as self.
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __buffer__(self, flags, /)
 |      Return a buffer object that exposes the underlying memory of the object.
 |
 |  __complex__(...)
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __copy__(...)
 |      a.__copy__()
 |
 |      Used if :func:`copy.copy` is called on an array. Returns a copy of the array.
 |
 |      Equivalent to ``a.copy(order='K')``.
 |
 |  __deepcopy__(...)
 |      a.__deepcopy__(memo, /)
 |
 |      Used if :func:`copy.deepcopy` is called on an array.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |
 |  __dlpack__(...)
 |      a.__dlpack__(*, stream=None)
 |
 |      DLPack Protocol: Part of the Array API.
 |
 |  __dlpack_device__(...)
 |      a.__dlpack_device__()
 |
 |      DLPack Protocol: Part of the Array API.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __float__(self, /)
 |      float(self)
 |
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |
 |  __format__(...)
 |      Default object formatter.
 |
 |      Return str(self) if format_spec is empty. Raise TypeError otherwise.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Return self+=value.
 |
 |  __iand__(self, value, /)
 |      Return self&=value.
 |
 |  __ifloordiv__(self, value, /)
 |      Return self//=value.
 |
 |  __ilshift__(self, value, /)
 |      Return self<<=value.
 |
 |  __imatmul__(self, value, /)
 |      Return self@=value.
 |
 |  __imod__(self, value, /)
 |      Return self%=value.
 |
 |  __imul__(self, value, /)
 |      Return self*=value.
 |
 |  __index__(self, /)
 |      Return self converted to an integer, if self is suitable for use as an index into a list.
 |
 |  __int__(self, /)
 |      int(self)
 |
 |  __invert__(self, /)
 |      ~self
 |
 |  __ior__(self, value, /)
 |      Return self|=value.
 |
 |  __ipow__(self, value, /)
 |      Return self**=value.
 |
 |  __irshift__(self, value, /)
 |      Return self>>=value.
 |
 |  __isub__(self, value, /)
 |      Return self-=value.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __itruediv__(self, value, /)
 |      Return self/=value.
 |
 |  __ixor__(self, value, /)
 |      Return self^=value.
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lshift__(self, value, /)
 |      Return self<<value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __matmul__(self, value, /)
 |      Return self@value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __neg__(self, /)
 |      -self
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __pos__(self, /)
 |      +self
 |
 |  __pow__(self, value, mod=None, /)
 |      Return pow(self, value, mod).
 |
 |  __radd__(self, value, /)
 |      Return value+self.
 |
 |  __rand__(self, value, /)
 |      Return value&self.
 |
 |  __rdivmod__(self, value, /)
 |      Return divmod(value, self).
 |
 |  __reduce__(...)
 |      a.__reduce__()
 |
 |      For pickling.
 |
 |  __reduce_ex__(...)
 |      Helper for pickle.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rfloordiv__(self, value, /)
 |      Return value//self.
 |
 |  __rlshift__(self, value, /)
 |      Return value<<self.
 |
 |  __rmatmul__(self, value, /)
 |      Return value@self.
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __rpow__(self, value, mod=None, /)
 |      Return pow(value, self, mod).
 |
 |  __rrshift__(self, value, /)
 |      Return value>>self.
 |
 |  __rshift__(self, value, /)
 |      Return self>>value.
 |
 |  __rsub__(self, value, /)
 |      Return value-self.
 |
 |  __rtruediv__(self, value, /)
 |      Return value/self.
 |
 |  __rxor__(self, value, /)
 |      Return value^self.
 |
 |  __setitem__(self, key, value, /)
 |      Set self[key] to value.
 |
 |  __setstate__(...)
 |      a.__setstate__(state, /)
 |
 |      For unpickling.
 |
 |      The `state` argument must be a sequence that contains the following
 |      elements:
 |
 |      Parameters
 |      ----------
 |      version : int
 |          optional pickle version. If omitted defaults to 0.
 |      shape : tuple
 |      dtype : data-type
 |      isFortran : bool
 |      rawdata : string or list
 |          a binary string with the data (or a list if 'a' is an object array)
 |
 |  __sizeof__(...)
 |      Size of object in memory, in bytes.
 |
 |  __str__(self, /)
 |      Return str(self).
 |
 |  __sub__(self, value, /)
 |      Return self-value.
 |
 |  __truediv__(self, value, /)
 |      Return self/value.
 |
 |  __xor__(self, value, /)
 |      Return self^value.
 |
 |  all(...)
 |      a.all(axis=None, out=None, keepdims=False, *, where=True)
 |
 |      Returns True if all elements evaluate to True.
 |
 |      Refer to `numpy.all` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.all : equivalent function
 |
 |  any(...)
 |      a.any(axis=None, out=None, keepdims=False, *, where=True)
 |
 |      Returns True if any of the elements of `a` evaluate to True.
 |
 |      Refer to `numpy.any` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.any : equivalent function
 |
 |  argmax(...)
 |      a.argmax(axis=None, out=None, *, keepdims=False)
 |
 |      Return indices of the maximum values along the given axis.
 |
 |      Refer to `numpy.argmax` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.argmax : equivalent function
 |
 |  argmin(...)
 |      a.argmin(axis=None, out=None, *, keepdims=False)
 |
 |      Return indices of the minimum values along the given axis.
 |
 |      Refer to `numpy.argmin` for detailed documentation.
 |
 |      See Also
 |      --------
 |      numpy.argmin : equivalent function
 |
 |  argpartition(...)
 |      a.argpartition(kth, axis=-1, kind='introselect', order=None)
 |
 |      Returns the indices that would partition this array.
 |
 |      Refer to `numpy.argpartition` for full documentation.
 |
 |      .. versionadded:: 1.8.0
 |
 |      See Also
 |      --------
 |      numpy.argpartition : equivalent function
 |
 |  argsort(...)
 |      a.argsort(axis=-1, kind=None, order=None)
 |
 |      Returns the indices that would sort this array.
 |
 |      Refer to `numpy.argsort` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.argsort : equivalent function
 |
 |  astype(...)
 |      a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
 |
 |      Copy of the array, cast to a specified type.
 |
 |      Parameters
 |      ----------
 |      dtype : str or dtype
 |          Typecode or data-type to which the array is cast.
 |      order : {'C', 'F', 'A', 'K'}, optional
 |          Controls the memory layout order of the result.
 |          'C' means C order, 'F' means Fortran order, 'A'
 |          means 'F' order if all the arrays are Fortran contiguous,
 |          'C' order otherwise, and 'K' means as close to the
 |          order the array elements appear in memory as possible.
 |          Default is 'K'.
 |      casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
 |          Controls what kind of data casting may occur. Defaults to 'unsafe'
 |          for backwards compatibility.
 |
 |            * 'no' means the data types should not be cast at all.
 |            * 'equiv' means only byte-order changes are allowed.
 |            * 'safe' means only casts which can preserve values are allowed.
 |            * 'same_kind' means only safe casts or casts within a kind,
 |              like float64 to float32, are allowed.
 |            * 'unsafe' means any data conversions may be done.
 |      subok : bool, optional
 |          If True, then sub-classes will be passed-through (default), otherwise
 |          the returned array will be forced to be a base-class array.
 |      copy : bool, optional
 |          By default, astype always returns a newly allocated array. If this
 |          is set to false, and the `dtype`, `order`, and `subok`
 |          requirements are satisfied, the input array is returned instead
 |          of a copy.
 |
 |      Returns
 |      -------
 |      arr_t : ndarray
 |          Unless `copy` is False and the other conditions for returning the input
 |          array are satisfied (see description for `copy` input parameter), `arr_t`
 |          is a new array of the same shape as the input array, with dtype, order
 |          given by `dtype`, `order`.
 |
 |      Notes
 |      -----
 |      .. versionchanged:: 1.17.0
 |         Casting between a simple data type and a structured one is possible only
 |         for "unsafe" casting.  Casting to multiple fields is allowed, but
 |         casting from multiple fields is not.
 |
 |      .. versionchanged:: 1.9.0
 |         Casting from numeric to string types in 'safe' casting mode requires
 |         that the string dtype length is long enough to store the max
 |         integer/float value converted.
 |
 |      Raises
 |      ------
 |      ComplexWarning
 |          When casting from complex to float or int. To avoid this,
 |          one should use ``a.real.astype(t)``.
 |
 |      Examples
 |      --------
 |      >>> x = np.array([1, 2, 2.5])
 |      >>> x
 |      array([1. ,  2. ,  2.5])
 |
 |      >>> x.astype(int)
 |      array([1, 2, 2])
 |
 |  byteswap(...)
 |      a.byteswap(inplace=False)
 |
 |      Swap the bytes of the array elements
 |
 |      Toggle between low-endian and big-endian data representation by
 |      returning a byteswapped array, optionally swapped in-place.
 |      Arrays of byte-strings are not swapped. The real and imaginary
 |      parts of a complex number are swapped individually.
 |
 |      Parameters
 |      ----------
 |      inplace : bool, optional
 |          If ``True``, swap bytes in-place, default is ``False``.
 |
 |      Returns
 |      -------
 |      out : ndarray
 |          The byteswapped array. If `inplace` is ``True``, this is
 |          a view to self.
 |
 |      Examples
 |      --------
 |      >>> A = np.array([1, 256, 8755], dtype=np.int16)
 |      >>> list(map(hex, A))
 |      ['0x1', '0x100', '0x2233']
 |      >>> A.byteswap(inplace=True)
 |      array([  256,     1, 13090], dtype=int16)
 |      >>> list(map(hex, A))
 |      ['0x100', '0x1', '0x3322']
 |
 |      Arrays of byte-strings are not swapped
 |
 |      >>> A = np.array([b'ceg', b'fac'])
 |      >>> A.byteswap()
 |      array([b'ceg', b'fac'], dtype='|S3')
 |
 |      ``A.newbyteorder().byteswap()`` produces an array with the same values
 |        but different representation in memory
 |
 |      >>> A = np.array([1, 2, 3])
 |      >>> A.view(np.uint8)
 |      array([1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
 |             0, 0], dtype=uint8)
 |      >>> A.newbyteorder().byteswap(inplace=True)
 |      array([1, 2, 3])
 |      >>> A.view(np.uint8)
 |      array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
 |             0, 3], dtype=uint8)
 |
 |  choose(...)
 |      a.choose(choices, out=None, mode='raise')
 |
 |      Use an index array to construct a new array from a set of choices.
 |
 |      Refer to `numpy.choose` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.choose : equivalent function
 |
 |  clip(...)
 |      a.clip(min=None, max=None, out=None, **kwargs)
 |
 |      Return an array whose values are limited to ``[min, max]``.
 |      One of max or min must be given.
 |
 |      Refer to `numpy.clip` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.clip : equivalent function
 |
 |  compress(...)
 |      a.compress(condition, axis=None, out=None)
 |
 |      Return selected slices of this array along given axis.
 |
 |      Refer to `numpy.compress` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.compress : equivalent function
 |
 |  conj(...)
 |      a.conj()
 |
 |      Complex-conjugate all elements.
 |
 |      Refer to `numpy.conjugate` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.conjugate : equivalent function
 |
 |  conjugate(...)
 |      a.conjugate()
 |
 |      Return the complex conjugate, element-wise.
 |
 |      Refer to `numpy.conjugate` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.conjugate : equivalent function
 |
 |  copy(...)
 |      a.copy(order='C')
 |
 |      Return a copy of the array.
 |
 |      Parameters
 |      ----------
 |      order : {'C', 'F', 'A', 'K'}, optional
 |          Controls the memory layout of the copy. 'C' means C-order,
 |          'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
 |          'C' otherwise. 'K' means match the layout of `a` as closely
 |          as possible. (Note that this function and :func:`numpy.copy` are very
 |          similar but have different default values for their order=
 |          arguments, and this function always passes sub-classes through.)
 |
 |      See also
 |      --------
 |      numpy.copy : Similar function with different default behavior
 |      numpy.copyto
 |
 |      Notes
 |      -----
 |      This function is the preferred method for creating an array copy.  The
 |      function :func:`numpy.copy` is similar, but it defaults to using order 'K',
 |      and will not pass sub-classes through by default.
 |
 |      Examples
 |      --------
 |      >>> x = np.array([[1,2,3],[4,5,6]], order='F')
 |
 |      >>> y = x.copy()
 |
 |      >>> x.fill(0)
 |
 |      >>> x
 |      array([[0, 0, 0],
 |             [0, 0, 0]])
 |
 |      >>> y
 |      array([[1, 2, 3],
 |             [4, 5, 6]])
 |
 |      >>> y.flags['C_CONTIGUOUS']
 |      True
 |
 |  cumprod(...)
 |      a.cumprod(axis=None, dtype=None, out=None)
 |
 |      Return the cumulative product of the elements along the given axis.
 |
 |      Refer to `numpy.cumprod` for full documentation.
 |
 |      See Also
 |      --------
 |      numpy.cumprod : equivalent function
 |
 |  cumsum(...)
 |      a.cumsum(axis=None, dtype=None, out=None)
 |

In [8]:
import sys

In [9]:
sys.getsizeof(5) * len(

SyntaxError: incomplete input (2344916994.py, line 1)

In [10]:
b = 100

In [11]:
sys.getsizeof(5) * len(b)

TypeError: object of type 'int' has no len()

In [12]:
b = range(100)
sys.getsizeof(5) * len(b)

2800

In [13]:
a.size*a.itemsize

16

In [14]:
a.size * a.itemsize

16

In [15]:
a = arange(100)

NameError: name 'arange' is not defined

In [16]:
a= np.arange(100)
a.itemsize * a.size

400

In [17]:
a.itemsize?

Type:        int
String form: 4
Docstring:
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating-point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

In [18]:
import time

In [19]:
time.time()

1773605443.323366

In [20]:
start = time.time()
a=np.arange(1000000000)

b=np.arange(1000000000)

a+b
end = time.time()

time2 =end - start

MemoryError: Unable to allocate 3.73 GiB for an array with shape (1000000000,) and data type int32

In [21]:
time2

NameError: name 'time2' is not defined

In [22]:
start = time.time()
a=range(1000000)

b=range(1000000)

z= [for x,y in zip(a,b)]
end = time.time()

time2 =end - start

SyntaxError: invalid syntax (439074377.py, line 6)

In [23]:
start = time.time()
l1=range(100000)
l2=range(100000)
res = [(x,y) for x,y in zip(l1,l2)]
end = time.time()
end - start

0.04108834266662598

In [24]:
a=np.arange(100000)
b=np.arange(100000)
start = time.time()

a+b
end = time.time()
end - start

0.010046958923339844

In [25]:
import numpy as np
sis = np.array([[1,2,3],[9,3,6],[44,34,88],[18,34,22],[34,45,100]])
sis

array([[  1,   2,   3],
       [  9,   3,   6],
       [ 44,  34,  88],
       [ 18,  34,  22],
       [ 34,  45, 100]])

In [26]:
sis.ndim

2

In [27]:
sis.size

15

In [28]:
sis.itemsize

4

In [29]:
sis = np.array([[1,2,3],[22,33,44]],dtype=np.float64)

In [30]:
sis.itemsize

8

In [31]:
sis = sis.astype(complex)

In [32]:
sis.itemsize

16

In [33]:
sis

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [22.+0.j, 33.+0.j, 44.+0.j]])

In [34]:
sis = sis.astype(int)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_31648\1646259465.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  sis = sis.astype(int)

In [35]:
z = np.array([[1,2,3],[4,5,6]])
z.sum()

21

In [36]:
z.sum(axis=0)

array([5, 7, 9])

In [37]:
z.sum(axis=1)

array([ 6, 15])

In [38]:
z.max()

6

In [39]:
z.min()

1

In [40]:
z.shape()

TypeError: 'tuple' object is not callable

In [41]:
z.shape

(2, 3)

In [42]:
z.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
z.ravel()

array([1, 2, 3, 4, 5, 6])

In [130]:
np.sqrt(x)

11.0

In [ ]:
np.linspace(1,6,7)

In [131]:
np.std(x)

0.0

In [132]:
np.mean(x)

121.0

In [133]:
np.median(x)

121.0

In [ ]:
np.arange(10)

In [48]:
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [ ]:
np.zeros((3,4))

In [49]:
np.ones((8,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [50]:
a = np.array([[1,2],[3,4],[5,6]])

In [51]:
b= np.array([[20,33],[30,50],[20,30]])

In [52]:
a+b

array([[21, 35],
       [33, 54],
       [25, 36]])

In [53]:
a-b

array([[-19, -31],
       [-27, -46],
       [-15, -24]])

In [54]:
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [55]:
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
a = np.array([[1,2],[3,4]])

In [56]:
b= np.array([[1,2],[3,4]])

In [57]:
a.dot(b)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [58]:
a=np.arange(16).reshape(4,4)

In [59]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
a[0,3]

3

In [61]:
a[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
a[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [63]:
a[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [64]:
for x in a:
    print(x)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]

In [65]:
for x in a.flat:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15

In [66]:
a=np.arange(6).reshape(3,2)

b = np.arange(6,12).reshape(3,2)

In [67]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [68]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [69]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [70]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [71]:
a=np.arange(30).reshape(2,15)

In [72]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [73]:
res = np.hsplit(a,3)

In [74]:
res

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [75]:
res[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [76]:
res[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [77]:
help(res)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __reversed__(self, /)
 |      Return a reverse iterator over the list.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __setitem__(self, key, value, /)
 |      Set self[key] to value.
 |
 |  __sizeof__(self, /)
 |      Return the size of the list in memory, in bytes.
 |
 |  append(self, object, /)
 |      Append object to the end of the list.
 |
 |  clear(self, /)
 |      Remove all items from list.
 |
 |  copy(self, /)
 |      Return a shallow copy of the list.
 |
 |  count(self, value, /)
 |      Return number of occurrences of value.
 |
 |  extend(self, iterable, /)
 |      Extend list by appending elements from the iterable.
 |
 |  index(self, value, start=0, stop=9223372036854775807, /)
 |      Return first index of value.
 |
 |      Raises ValueError if the value is not present.
 |
 |  insert(self, index, object, /)
 |      Insert object before index.
 |
 |  pop(self, index=-1, /)
 |      Remove and return item at index (default last).
 |
 |      Raises IndexError if list is empty or index is out of range.
 |
 |  remove(self, value, /)
 |      Remove first occurrence of value.
 |
 |      Raises ValueError if the value is not present.
 |
 |  reverse(self, /)
 |      Reverse *IN PLACE*.
 |
 |  sort(self, /, *, key=None, reverse=False)
 |      Sort the list in ascending order and return None.
 |
 |      The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
 |      order of two equal elements is maintained).
 |
 |      If a key function is given, apply it once to each list item and sort them,
 |      ascending or descending, according to their function values.
 |
 |      The reverse flag can be set to sort in descending order.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  __class_getitem__(...)
 |      See PEP 585
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __hash__ = None

In [78]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [79]:
a=np.arange(12).reshape(3,4)

In [80]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
b=a>4

In [82]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [83]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [84]:
a[b]=0

In [85]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [86]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11

In [88]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11

In [89]:
for x in np.nditer(a,order="F",flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]

In [90]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [91]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [92]:
b=np.arange(3,10,3).reshape(3,1)

In [93]:
b

array([[3],
       [6],
       [9]])

In [94]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 6
25 6
36 6
49 6
64 9
81 9
100 9
121 9

In [95]:
import pandas as pd
df = pd.read_csv("nyc_weather.csv")

In [96]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [97]:
df['Temperature'].max()

50

In [98]:
df['EST'][df['Events']=="Rain"]

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [99]:
df.fillna(0,inplace=True)

In [100]:
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,0,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,0,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,0,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,0,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,0,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,0,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,0,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,0.0,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,0.0,0,1,0,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,0,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,0,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,0,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,0,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,0,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,0,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,0,312
21,1/22/2016,26,6,41,30.21,9,0.0,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,0,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,0,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,0,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,0,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,0,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,0,241

In [101]:
df['WindSpeedMPH'].mean()

6.225806451612903

In [102]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,0,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,0,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,0,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,0,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333

In [103]:
df.shape

(31, 11)

In [104]:
rows , cols = df.shape

In [105]:
rows

31

In [106]:
cols

11

In [107]:
df.tail()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,0,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,0,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,0,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,0,241

In [108]:
df[4:9]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,0,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,0,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,0,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76

In [109]:
df['Temperature']

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [110]:
df.Temperature

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [111]:
df[['Temperature','Humidity','Events']]

    Temperature  Humidity    Events
0            38        52         0
1            36        46         0
2            40        47         0
3            25        44         0
4            20        41         0
5            33        35         0
6            39        33         0
7            39        64         0
8            44        77      Rain
9            50        71      Rain
10           33        37         0
11           35        53         0
12           26        42         0
13           30        47         0
14           43        62         0
15           47        70      Rain
16           36        66  Fog-Snow
17           25        53      Snow
18           22        42         0
19           32        49         0
20           31        45         0
21           26        41      Snow
22           26        78  Fog-Snow
23           28        53      Snow
24           34        54         0
25           43        56         0
26           41        45      Rain
27           37        51         0
28           36        50         0
29           34        46         0
30           46        52         0

In [112]:
df['Temperature'][df.Temperature == df.Temperature.max()]

9    50
Name: Temperature, dtype: int64

In [113]:
df[['Temperature','Humidity']][df['Humidity']==df['Humidity'].max()]

    Temperature  Humidity
22           26        78

In [114]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.225806,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,3.422569,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,0.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.000000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [115]:
df.VisibilityMiles.max()

10

In [116]:
df.set_index('Temperature')

,EST,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Temperature,,,,,,,,,,
38,1/1/2016,23,52,30.03,10,8.0,0,5,0,281
36,1/2/2016,18,46,30.02,10,7.0,0,3,0,275
40,1/3/2016,21,47,29.86,10,8.0,0,1,0,277
25,1/4/2016,9,44,30.05,10,9.0,0,3,0,345
20,1/5/2016,-3,41,30.57,10,5.0,0,0,0,333
33,1/6/2016,4,35,30.50,10,4.0,0,0,0,259
39,1/7/2016,11,33,30.28,10,2.0,0,3,0,293
39,1/8/2016,29,64,30.20,10,4.0,0,8,0,79
44,1/9/2016,38,77,30.16,9,8.0,T,8,Rain,76
50,1/10/2016,46,71,29.59,4,0.0,1.8,7,Rain,109
33,1/11/2016,8,37,29.92,10,0.0,0,1,0,289
35,1/12/2016,15,53,29.85,10,6.0,T,4,0,235
26,1/13/2016,4,42,29.94,10,10.0,0,0,0,284
30,1/14/2016,12,47,29.95,10,5.0,T,7,0,266
43,1/15/2016,31,62,29.82,9,5.0,T,2,0,101
47,1/16/2016,37,70,29.52,8,7.0,0.24,7,Rain,340
36,1/17/2016,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
25,1/18/2016,6,53,29.83,9,12.0,T,2,Snow,293
22,1/19/2016,3,42,30.03,10,11.0,0,1,0,293
32,1/20/2016,15,49,30.13,10,6.0,0,2,0,302
31,1/21/2016,11,45,30.15,10,6.0,0,1,0,312
26,1/22/2016,6,41,30.21,9,0.0,0.01,3,Snow,34
26,1/23/2016,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
28,1/24/2016,11,53,29.92,8,6.0,T,3,Snow,327
34,1/25/2016,18,54,30.25,10,3.0,0,2,0,286
43,1/26/2016,29,56,30.03,10,7.0,0,2,0,244
41,1/27/2016,22,45,30.03,10,7.0,T,3,Rain,311
37,1/28/2016,20,51,29.90,10,5.0,0,1,0,234
36,1/29/2016,21,50,29.58,10,8.0,0,4,0,298
34,1/30/2016,16,46,30.01,10,7.0,0,0,0,257
46,1/31/2016,28,52,29.90,10,5.0,0,0,0,241

In [117]:
df.set_index('Temperature',inplace=True)

In [118]:
df.head()

,EST,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Temperature,,,,,,,,,,
38,1/1/2016,23,52,30.03,10,8.0,0,5,0,281
36,1/2/2016,18,46,30.02,10,7.0,0,3,0,275
40,1/3/2016,21,47,29.86,10,8.0,0,1,0,277
25,1/4/2016,9,44,30.05,10,9.0,0,3,0,345
20,1/5/2016,-3,41,30.57,10,5.0,0,0,0,333

In [119]:
df.reset_index(inplace=True)

In [120]:
df.head(1)

,Temperature,EST,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,38,1/1/2016,23,52,30.03,10,8.0,0,5,0,281

In [121]:
df.loc[38]

KeyError: 38

In [122]:
df.set_index('Sea Level PressureIn',inplace=True)

In [123]:
df.tail(10)

,Temperature,EST,DewPoint,Humidity,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
Sea Level PressureIn,,,,,,,,,,
30.21,26,1/22/2016,6,41,9,0.0,0.01,3,Snow,34
29.77,26,1/23/2016,21,78,1,16.0,2.31,8,Fog-Snow,42
29.92,28,1/24/2016,11,53,8,6.0,T,3,Snow,327
30.25,34,1/25/2016,18,54,10,3.0,0,2,0,286
30.03,43,1/26/2016,29,56,10,7.0,0,2,0,244
30.03,41,1/27/2016,22,45,10,7.0,T,3,Rain,311
29.90,37,1/28/2016,20,51,10,5.0,0,1,0,234
29.58,36,1/29/2016,21,50,10,8.0,0,4,0,298
30.01,34,1/30/2016,16,46,10,7.0,0,0,0,257
29.90,46,1/31/2016,28,52,10,5.0,0,0,0,241

In [124]:
df.loc[30.21]

Temperature               26
EST                1/22/2016
DewPoint                   6
Humidity                  41
VisibilityMiles            9
WindSpeedMPH             0.0
PrecipitationIn         0.01
CloudCover                 3
Events                  Snow
WindDirDegrees            34
Name: 30.21, dtype: object

In [125]:

weather_data = {
'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
'temperature': [32, 35, 28],
'windspeed': [6,7,2],
'event': ['Rain', 'Sunny', 'Snow']
}


df = pd.DataFrame(weather_data)

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [126]:

# way 4 (python tuple list)
weather_data = [
('1/1/2017', 32, 6, 'Rain'),
('1/2/2017', 35, 7, 'Sunny'),
('1/3/2017', 28, 2, 'Snow')
]

df = pd.DataFrame(weather_data,columns=["day",'temp',"speed","event"])

In [127]:
df

        day  temp  speed  event
0  1/1/2017    32      6   Rain
1  1/2/2017    35      7  Sunny
2  1/3/2017    28      2   Snow

In [128]:
# way 5 (python dictionary list)
weather_data = [
{'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
{'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
{'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'}
]

df = pd.DataFrame(weather_data)

In [129]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow